
version: '3'
services:
  mental-training-mongo:
    container_name: mt-monga
    restart: unless-stopped
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASS}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASS=${MONGODB_PASS}
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - dbdata:/data/db
    ports:
      - "${MONGODB_PORT}:27017"
    networks:
      - training-network
  mental-training-redis:
    container_name: mt-redis
    image: redis:latest
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: unless-stopped
    volumes:
      - redis-data:/data
    expose:
      - 6379
    ports:
      - "${REDIS_PORT}:6379"
networks:
  training-network: